// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sngufjcyspehlnrkqgry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuZ3VmamN5c3BlaGxucmtxZ3J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTAxMTksImV4cCI6MjA2NDE2NjExOX0.cc0tmI4Ks4I1oYRe0AYYKsKM57G8HAmzZ3c7dgP_iRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
